runtime: python3111
env: flex
entrypoint: gunicorn -b :$PORT Flask_app:app

env_variables:
  OPENAI_API_KEY: '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'
  DEBATER_API_KEY: 'a64e50a6f01001a93d47d7e32a646515L05'

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7

network:
  session_affinity: true

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

readiness_check:
  path: "/readiness_check"
  timeout_sec: 4
  check_interval_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/liveness_check"
  timeout_sec: 4
  check_interval_sec: 30
  failure_threshold: 2
  success_threshold: 2
